"""Add password_hash to User model

Revision ID: 66858370f3b2
Revises: 4feedbdeb587
Create Date: 2025-09-24 22:13:58.135517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66858370f3b2'
down_revision = '4feedbdeb587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
