"""Add Brand model and deal_percentage to Product

Revision ID: ccc30f83fa5b
Revises: 4cc91dd35e46
Create Date: 2025-09-26 09:46:54.423594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc30f83fa5b'
down_revision = '4cc91dd35e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('deal_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deal_percentage')
    op.drop_table('brands')
    # ### end Alembic commands ###
