"""Add stock column to Product model

Revision ID: cfa9226e4e9b
Revises: fdcbbaa17918
Create Date: 2025-09-25 20:38:27.481954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa9226e4e9b'
down_revision = 'fdcbbaa17918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
